# Site
name: "Giá gạch bông gió xi măng | Giá gạch bông "
title: "Báo giá gạch bông gió xi măng"
description: "Giá gạch bông gió xi măng & gạch bông giá rẻ"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: cans@cementtile.vn

# Authors
authors:
  sal:
    name: David
    display_name: David
    avatar: 'assets/images/avatar-sal.png'
    email: cans@cementtile.vn
    web: https://baogiagachbong.netlify.app/
    twitter: https://twitter.com/vietnamtiles
    description: "Blog của tôi nói về giá gạch bông, giá gạch bông gió xi măng"
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    email: cans@cementtile.vn
    web: https://baogiagachbong.netlify.app/
    twitter: https://twitter.com/vietnamtiles
    description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-admin
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
